name: sagitta
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - ta-lib

  - pip:
      - -e .
      - tensorflow==2.20.0
      - tensorflow-metal==1.2.0
      - torch
      - optuna
      - snakemake
      - python-binance