# Paths for workflow
paths:
  keys_path:       "config/secrets/keys.json"
  download_script: "workflow/scripts/fetch/download_market_test_data.py"

# Define market to fetch
client:
  pair:   "ETHUSDT"
  period: "1h"
  start:  "720d"